name: commands

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  retest:
    if: |
      ${{
         github.event.issue.pull_request
         && github.repository == 'envoyproxy/envoy'
         && github.actor != 'repokitteh-read-only[bot]'
         && github.actor != 'dependabot[bot]'
      }}
    name: Retest
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      actions: write
    steps:
    - uses: envoyproxy/toolshed/gh-actions/retest@550585367f05177a3d4193bf1410e7b6a26142cd
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
